@startuml

title Singleton Pattern - Logger

class Logger {
    +getLoggerInstance(): Logger&
    +Log(): void

    -Logger()
    -Logger (const Logger&) = delete
    -Logger& operator=(const Logger&) = delete
    -Logger (Logger&&) = delete
    -Logger& operator=(Logger&&) = delete

    ~Logger() = default
}

@enduml
